### ISSUE TITLE
Package requires minimum stability dev

### ISSUE THREAD

**Issue by mattbucci** [alcohol/oauth2-eveonline#1]
You may want to tag a 1.0 release as right now it's not possible to install via the readme if you don't have "minimum-stability": "dev" in your composer.json

**Comment by alcohol** [comment]
Yea, you'll have to use `composer require alcohol/oauth2-eveonline:dev-master`.

I had something in the back of my mind that I wanted to check on, but I can't recall right now what it was. If it doesn't pop back in before the end of the day, I'll tag a stable release.

**Comment by alcohol** [comment]
Tagged a provisional 0.1.0 release for now. Not quite "stable" yet, but at least you can set a normal constraint on it (e.g. `^0.1`).
