### ISSUE TITLE
Typehinting Void is a php7.1 feature

### ISSUE THREAD

**Issue by mattbucci** [alcohol/oauth2-eveonline#2]
Running on php7.0 the package throws a typerror.

If you're going to use the void keyword it looks like you should bump the min composer require to ^7.1.0, but as 7.1 is so bleeding edge I'd recommend just forgoing the typehint in this case.

![screen shot 2017-02-28 at 11 46 30 pm](https://cloud.githubusercontent.com/assets/3284147/23450493/4fc46b48-fe10-11e6-9c40-2bd5578943d3.jpg)

**Comment by alcohol** [comment]
Ah, all my Arch systems run 7.1 already so I had not noticed. I figured phpstorm would probably complain about it, but maybe I forgot to specify 7.0 as the target version. Thanks for letting me know.

**Comment by alcohol** [comment]
Should be fixed in the 0.2.0 release.
